<?php
	$tpl = array(
	
		array(
			'tpltypeid'=>1,
			'tplview'=>'cate1.png',
			'tpltypename'=>'101_index',
			'tpldesinfo'=>'',
			'attr'=>'thumb focu bgs',
			'sort'=>1,
		),	
		
		array(
			'tpltypeid'=>2,
			'tplview'=>'cate2.png',
			'tpltypename'=>'102_index',
			'tpldesinfo'=>'列表式图片模版，缩略图建议使用150*150或近似尺寸比例的图片。',
			'attr'=>'focu bgs lis',
			'sort'=>2,
		),
		
		array(
			'tpltypeid'=>3,
			'tplview'=>'cate3.png',
			'tpltypename'=>'103_index',
			'tpldesinfo'=>'列表式图片模版，缩略图建议使用150*150或近似尺寸比例的图片。',
			'attr'=>'focu bgs lis',
			'sort'=>3,
		),
				
		array(
			'tpltypeid'=>4,
			'tplview'=>'cate4.png',
			'tpltypename'=>'104_index',
			'tpldesinfo'=>'列表式图片模版，缩略图建议使用150*150或近似尺寸比例的图片。',
			'attr'=>'thumb focu bgs lis',
			'sort'=>4,
		),
						
		array(
			'tpltypeid'=>5,
			'tplview'=>'cate9.png',
			'tpltypename'=>'105_index',
			'tpldesinfo'=>'文字标签式模版，顶部幻灯片尺寸为640*320或近似等比例图片。',
			'attr'=>'focu bgs',
			'sort'=>5,
		),
								
		array(
			'tpltypeid'=>6,
			'tplview'=>'cate106.png',
			'tpltypename'=>'106_index_ydkds',
			'tpldesinfo'=>'',
			'attr'=>'focu thumb bgs',
			'sort'=>6,
		),
										
		array(
			'tpltypeid'=>7,
			'tplview'=>'cate107.png',
			'tpltypename'=>'107_index_2d8si',
			'tpldesinfo'=>'',
			'attr'=>'focu thumb bgs',
			'sort'=>7,
		),

		array(
			'tpltypeid'=>8,
			'tplview'=>'cate108.png',
			'tpltypename'=>'108_index_giw93x',
			'tpldesinfo'=>'',
			'attr'=>'filt focu bgs',
			'sort'=>8,
		),
		
		array(
			'tpltypeid'=>9,
			'tplview'=>'cate109.png',
			'tpltypename'=>'109_index_0fdis',
			'tpldesinfo'=>'',
			'attr'=>'focu bgs',
			'sort'=>9,
		),
				
		array(
			'tpltypeid'=>10,
			'tplview'=>'cate110.png',
			'tpltypename'=>'110_index_2skz7',
			'tpldesinfo'=>'',
			'attr'=>'bgs focu thumb',
			'sort'=>10,
		),
						
		array(
			'tpltypeid'=>11,
			'tplview'=>'cate111.png',
			'tpltypename'=>'111_index_78yus',
			'tpldesinfo'=>'左右图文式模版，顶部幻灯片建议使用尺寸为640*320或近似等比例图片；分类图片建议使用450*300或近似等比例图片，请不要使用高度大于或接近于宽度的图片。',
			'attr'=>'bgs focu thumb',
			'sort'=>11,
		),

		array(
			'tpltypeid'=>12,
			'tplview'=>'cate112.png',
			'tpltypename'=>'112_index_kj7y5',
			'tpldesinfo'=>'',
			'attr'=>'bg bgs filt',
			'sort'=>12,
		),
		
		array(
			'tpltypeid'=>13,
			'tplview'=>'cate113.png',
			'tpltypename'=>'113_index_jks6z',
			'tpldesinfo'=>'',
			'attr'=>'bg bgs filt',
			'sort'=>13,
		),
		
		array(
			'tpltypeid'=>14,
			'tplview'=>'cate114.png',
			'tpltypename'=>'114_index_mnsz6',
			'tpldesinfo'=>'',
			'attr'=>'thumb filt bg bgs',
			'sort'=>14,
		),
		
		array(
			'tpltypeid'=>15,
			'tplview'=>'cate115.png',
			'tpltypename'=>'115_index_ms76x',
			'tpldesinfo'=>'',
			'attr'=>'bgs bg filt',
			'sort'=>15,
		),
		
		array(
			'tpltypeid'=>16,
			'tplview'=>'cate116.png',
			'tpltypename'=>'116_index_ms76x',
			'tpldesinfo'=>'图片式模板，顶部幻灯片建议尺寸为宽640*高320或近似等比例的图片，文字为分类名称及分类描述，名称建议4个字符，描述限制10个字符以内；图片为分类封面，建议尺寸为宽165*高100或近似等比例图片',
			'attr'=>'thumb focu bgs',
			'sort'=>16,
		),
		
		array(
			'tpltypeid'=>17,
			'tplview'=>'cate117.png',
			'tpltypename'=>'117_index_usn3x',
			'tpldesinfo'=>'图标式模板',
			'attr'=>'thumb filt bg bgs',
			'sort'=>17,
		),
		
		array(
			'tpltypeid'=>18,
			'tplview'=>'cate118.png',
			'tpltypename'=>'118_index_jge3',
			'tpldesinfo'=>'图标式模板，顶部幻灯片建议尺寸为宽640*高320或近似等比例的图片。',
			'attr'=>'thumb focu bgs',
			'sort'=>18,
		),
		
		array(
			'tpltypeid'=>19,
			'tplview'=>'cate119.png',
			'tpltypename'=>'119_index_jsg2',
			'tpldesinfo'=>'图标式模板，顶部幻灯片建议尺寸为宽640*高320或近似等比例的图片。',
			'attr'=>'focu thumb bgs',
			'sort'=>19,
		),
		
		array(
			'tpltypeid'=>20,
			'tplview'=>'cate120.png',
			'tpltypename'=>'120_index_pfs9',
			'tpldesinfo'=>'支持二级分类，顶部幻灯片建议尺寸为宽640*高320或近似等比例的图片，幻灯下4个图标为分类管理的前4个分类，图标下第一块内容为第五个分类的分类封面、分类名称及子分类名称，建议尺寸300*300或1:1图片，下面依次类推。',
			'attr'=>'focu thumb bgs',
			'sort'=>20,
		),
		
		array(
			'tpltypeid'=>21,
			'tplview'=>'cate121.png',
			'tpltypename'=>'121_index_eor5w',
			'tpldesinfo'=>'图标式模板，顶部幻灯片建议尺寸为宽640*高320或近似等比例的图片，分类前8个为图标及文字展示，后面分类为图片展示，建议尺寸为宽150*高90或等比例图片。',
			'attr'=>'focu bgs thumb',
			'sort'=>21,
		),

		array(
			'tpltypeid'=>22,
			'tplview'=>'cate122.png',
			'tpltypename'=>'122_index_pgj9d',
			'tpldesinfo'=>'图标式模板，按分类顺序依次展现，有图片显示的分类，图片尺寸建议为宽150*85高或的等比例图片。',
			'attr'=>'bgs thumb',
			'sort'=>22,
		),
		
		array(
			'tpltypeid'=>23,
			'tplview'=>'cate123.png',
			'tpltypename'=>'123_index_jge4s',
			'tpldesinfo'=>'汽车行业专属模板，顶部幻灯片建议尺寸为宽640*高320或近似等比例的图片，幻灯下4个图标为分类管理的前4个分类，后面分类依次展示，图片建议尺寸为宽302*高233或等比例图片，logo图标为官网logo，需等比尺寸的png格式图片。',
			'attr'=>'focu bgs',
			'sort'=>23,
		),
		
		array(
			'tpltypeid'=>24,
			'tplview'=>'cate124.png',
			'tpltypename'=>'124_index_ghe5s',
			'tpldesinfo'=>'此模板适合做简单版纯展示的会员卡，头部图片就是首页封面图，宽720高随便，如果用幻灯片记住一定要相同的尺寸。小图标尺寸是正方形300x300,一个分类一页显示8个二级分类。',
			'attr'=>'sub focu bgs thumb',
			'sort'=>24,
		),
		
		array(
			'tpltypeid'=>25,
			'tplview'=>'cate125.png',
			'tpltypename'=>'125_index_gjnh4',
			'tpldesinfo'=>'左右双栏模版，顶部幻灯片尺寸为640*320或近似等比例图片，如使用正方形图片会使得页面不美观；分类图片建议使用300*200或近似等比例图片，使用宽度小于高度的(如200*300)尺寸图片将使页面惨不忍睹。',
			'attr'=>'bgs focu thumb',
			'sort'=>25,
		),
		
		array(
			'tpltypeid'=>26,
			'tplview'=>'cate126.png',
			'tpltypename'=>'126_index_gjj0f',
			'tpldesinfo'=>'图标式模版，顶部幻灯片建议使用尺寸为640*320或近似等比例图片；分类图片请使用正方形尺寸的图片。',
			'attr'=>'focu thumb bgs',
			'sort'=>26,
		),
		
		array(
			'tpltypeid'=>27,
			'tplview'=>'cate127.png',
			'tpltypename'=>'127_index_jpr4g',
			'tpldesinfo'=>'',
			'attr'=>'focu bgs thumb',
			'sort'=>27,
		),
		
		array(
			'tpltypeid'=>28,
			'tplview'=>'cate128.png',
			'tpltypename'=>'128_index_pgj3f',
			'tpldesinfo'=>'图标式模版，顶部幻灯片建议使用尺寸为640*320或近似等比例图片；分类图片请使用正方形尺寸的图片。',
			'attr'=>'focu bgs thumb',
			'sort'=>28,
		),
		
		array(
			'tpltypeid'=>29,
			'tplview'=>'cate129.png',
			'tpltypename'=>'129_index_fds3f',
			'tpldesinfo'=>'图标式模版，顶部幻灯片建议使用尺寸为640*320或近似等比例图片；分类图片请使用正方形尺寸的图片。',
			'attr'=>'focu bgs thumb',
			'sort'=>29,
		),
		
		array(
			'tpltypeid'=>30,
			'tplview'=>'cate130.png',
			'tpltypename'=>'130_index_ves7g',
			'tpldesinfo'=>'图标式模版，顶部幻灯片建议使用尺寸为640*320或近似等比例图片；分类图片请使用正方形尺寸的图片。',
			'attr'=>'focu bgs thumb',
			'sort'=>30,
		),

		array(
			'tpltypeid'=>31,
			'tplview'=>'cate131.png',
			'tpltypename'=>'131_index_win6a',
			'tpldesinfo'=>'此模板适合做简单版纯展示的会员卡，头部图片就是首页封面图，宽720高随便，如果用幻灯片记住一定要相同的尺寸。小图标尺寸是正方形300x300,一个分类一页显示8个二级分类。',
			'attr'=>'sub focu bgs thumb',
			'sort'=>31,
		),
		
		array(
			'tpltypeid'=>32,
			'tplview'=>'cate132.png',
			'tpltypename'=>'132_index_wio1a',
			'tpldesinfo'=>'此模板适合做简单版纯展示的会员卡，头部图片就是首页封面图，宽720高随便，如果用幻灯片记住一定要相同的尺寸。小图标尺寸是正方形300x300,一个分类一页显示6个二级分类。',
			'attr'=>'sub focu bgs thumb',
			'sort'=>32,
		),
		
		array(
			'tpltypeid'=>33,
			'tplview'=>'cate133.png',
			'tpltypename'=>'133_index_wis2a',
			'tpldesinfo'=>'此模板支持二级分类，适合分类比较多的地方公众号，小图标为正方形300x300px。',
			'attr'=>'sub focu bgs thumb',
			'sort'=>33,
		),
		
		array(
			'tpltypeid'=>34,
			'tplview'=>'cate134.png',
			'tpltypename'=>'134_index_viw3a',
			'tpldesinfo'=>'此模板支持二级分类，适合分类比较多的地方公众号，小图标为正方形300x300px。',
			'attr'=>'sub focu bgs thumb',
			'sort'=>34,
		),
		
		array(
			'tpltypeid'=>35,
			'tplview'=>'cate135.png',
			'tpltypename'=>'135_index_you4a',
			'tpldesinfo'=>'此模板支持二级分类，适合分类比较多的地方公众号，前4个一级分类可以突出显示，小图标',
			'attr'=>'focu bgs thumb',
			'sort'=>35,
		),		
		array(
			'tpltypeid'=>36,
			'tplview'=>'cate136.png',
			'tpltypename'=>'136_index_esfsd344',
			'tpldesinfo'=>'',
			'attr'=>'thumb bg bgs filt',
			'sort'=>36,
		),
		array(
			'tpltypeid'=>37,
			'tplview'=>'list1.png',
			'tpltypename'=>'yl_list',
			'tpldesinfo'=>'',
			'attr'=>'lis',
			'sort'=>37,
		),
		array(
			'tpltypeid'=>38,
			'tplview'=>'list4.png',
			'tpltypename'=>'ktv_list',
			'tpldesinfo'=>'',
			'attr'=>'lis',
			'sort'=>38,
		),
		array(
			'tpltypeid'=>39,
			'tplview'=>'cate139.png',
			'tpltypename'=>'139_index_ktv',
			'tpldesinfo'=>'小图标为正方形300x300px。不支持更换颜色风格',
			'attr'=>'focu thumb filt',
			'sort'=>39,
		),
		array(
			'tpltypeid'=>40,
			'tplview'=>'cate140.png',
			'tpltypename'=>'140_index_qesf',
			'tpldesinfo'=>'小图标为正方形300x300px。不支持更换颜色风格',
			'attr'=>'focu thumb bgs',
			'sort'=>40,
		),
		array(
			'tpltypeid'=>41,
			'tplview'=>'cate141.png',
			'tpltypename'=>'141_index_654d',
			'tpldesinfo'=>'小图标为正方形300x300px。不支持更换颜色风格',
			'attr'=>'focu thumb bgs',
			'sort'=>41,
		),
		array(
			'tpltypeid'=>42,
			'tplview'=>'cate142.png',
			'tpltypename'=>'142_index_6uid',
			'tpldesinfo'=>'无头部幻灯片，小图标为正方形300x300px。不支持更换颜色风格',
			'attr'=>'bgs filt bg thumb',
			'sort'=>42,
		),
		array(
			'tpltypeid'=>43,
			'tplview'=>'cate143.png',
			'tpltypename'=>'143_index_53sd',
			'tpldesinfo'=>'无头部幻灯片，小图标为正方形300x300px。不支持更换颜色风格',
			'attr'=>'bgs filt bg thumb',
			'sort'=>43,
		),
		array(
			'tpltypeid'=>44,
			'tplview'=>'cate144.png',
			'tpltypename'=>'144_index_bfst',
			'tpldesinfo'=>'无头部幻灯片，小图标为正方形300x300px。不支持更换颜色风格',
			'attr'=>'bgs bg thumb',
			'sort'=>44,
		),
		array(
			'tpltypeid'=>45,
			'tplview'=>'cate145.png',
			'tpltypename'=>'145_index_vbws',
			'tpldesinfo'=>'小图标为正方形300x300px。不支持更换颜色风格',
			'attr'=>'bgs thumb focu',
			'sort'=>45,
		),
		array(
			'tpltypeid'=>46,
			'tplview'=>'cate146.png',
			'tpltypename'=>'146_index_58sv',
			'tpldesinfo'=>'小图标为正方形300x300px。不支持更换颜色风格',
			'attr'=>'bgs thumb focu',
			'sort'=>46,
		),
		array(
			'tpltypeid'=>47,
			'tplview'=>'cate147.png',
			'tpltypename'=>'147_index_verm',
			'tpldesinfo'=>'小图标为正方形300x300px。不支持更换颜色风格',
			'attr'=>'bgs thumb focu',
			'sort'=>47,
		),
		array(
			'tpltypeid'=>48,
			'tplview'=>'cate148.png',
			'tpltypename'=>'148_index_bleu',
			'tpldesinfo'=>'小图标为正方形300x300px。不支持更换颜色风格',
			'attr'=>'bgs thumb focu',
			'sort'=>48,
		),
		array(
			'tpltypeid'=>49,
			'tplview'=>'cate149.png',
			'tpltypename'=>'149_index_28ad',
			'tpldesinfo'=>'小图标为正方形300x300px。不支持更换颜色风格',
			'attr'=>'bgs thumb focu',
			'sort'=>49,
		),
		array(
			'tpltypeid'=>50,
			'tplview'=>'cate150.png',
			'tpltypename'=>'150_index_28sv',
			'tpldesinfo'=>'小图标为正方形300x300px。不支持更换颜色风格',
			'attr'=>'bgs thumb focu',
			'sort'=>50,
		),
		array(
			'tpltypeid'=>51,
			'tplview'=>'cate151.png',
			'tpltypename'=>'151_index_ve4y',
			'tpldesinfo'=>'小图标为正方形300x300px。不支持更换颜色风格',
			'attr'=>'bgs thumb focu',
			'sort'=>51,
		),
		array(
			'tpltypeid'=>52,
			'tplview'=>'cate152.png',
			'tpltypename'=>'152_index_v82x',
			'tpldesinfo'=>'小图标为正方形300x300px。不支持更换颜色风格',
			'attr'=>'bgs thumb focu',
			'sort'=>52,
		),
		array(
			'tpltypeid'=>53,
			'tplview'=>'cate153.png',
			'tpltypename'=>'153_index_58sdf',
			'tpldesinfo'=>'诺基亚X风格，披着wp外衣的android，不支持更换颜色风格',
			'attr'=>'bgs thumb focu',
			'sort'=>53,
		),
		array(
			'tpltypeid'=>54,
			'tplview'=>'cate154.png',
			'tpltypename'=>'154_index_f78d1',
			'tpldesinfo'=>'诺基亚X风格2，不支持更换颜色风格',
			'attr'=>'bgs thumb focu',
			'sort'=>54,
		),
		array(
			'tpltypeid'=>55,
			'tplview'=>'cate155.png',
			'tpltypename'=>'155_index_xym7',
			'tpldesinfo'=>'小图标为正方形300x300px。不支持更换颜色风格',
			'attr'=>'bgs thumb focu',
			'sort'=>55,
		),
		array(
			'tpltypeid'=>56,
			'tplview'=>'cate156.png',
			'tpltypename'=>'156_index_64ay',
			'tpldesinfo'=>'小图标为正方形300x300px。不支持更换颜色风格',
			'attr'=>'bgs thumb focu',
			'sort'=>56,
		),
		array(
			'tpltypeid'=>57,
			'tplview'=>'cate157.png',
			'tpltypename'=>'157_index_dgeh7',
			'tpldesinfo'=>'小图标为正方形300x300px。不支持更换颜色风格',
			'attr'=>'bgs thumb focu',
			'sort'=>57,
		),
		array(
			'tpltypeid'=>58,
			'tplview'=>'cate158.png',
			'tpltypename'=>'158_index_ffy4',
			'tpldesinfo'=>'小图标为正方形300x300px。不支持更换颜色风格',
			'attr'=>'bgs thumb focu',
			'sort'=>58,
		),
		array(
			'tpltypeid'=>59,
			'tplview'=>'cate159.png',
			'tpltypename'=>'159_index_fgft',
			'tpldesinfo'=>'小图标为正方形300x300px。不支持更换颜色风格',
			'attr'=>'bgs thumb focu',
			'sort'=>59,
		),
		array(
			'tpltypeid'=>60,
			'tplview'=>'cate160.png',
			'tpltypename'=>'160_index_674f',
			'tpldesinfo'=>'小图标为正方形300x300px。不支持更换颜色风格',
			'attr'=>'bgs thumb focu',
			'sort'=>60,
		),
		array(
			'tpltypeid'=>61,
			'tplview'=>'cate161.png',
			'tpltypename'=>'161_index_df3t',
			'tpldesinfo'=>'小图标为正方形300x300px。不支持更换颜色风格',
			'attr'=>'bgs thumb focu',
			'sort'=>61,
		),
		array(
			'tpltypeid'=>62,
			'tplview'=>'cate162.png',
			'tpltypename'=>'162_index_xffe',
			'tpldesinfo'=>'小图标为正方形300x300px。不支持更换颜色风格',
			'attr'=>'bgs thumb focu',
			'sort'=>62,
		),
		array(
			'tpltypeid'=>63,
			'tplview'=>'cate163.png',
			'tpltypename'=>'163_index_cve3',
			'tpldesinfo'=>'小图标为正方形300x300px。不支持更换颜色风格',
			'attr'=>'bgs thumb focu',
			'sort'=>63,
		),
		array(
			'tpltypeid'=>64,
			'tplview'=>'cate164.png',
			'tpltypename'=>'164_index_5366',
			'tpldesinfo'=>'小图标为正方形300x300px。不支持更换颜色风格',
			'attr'=>'bgs thumb focu filt lis',
			'sort'=>64,
		),
		array(
			'tpltypeid'=>65,
			'tplview'=>'cate165.png',
			'tpltypename'=>'165_index_6dgbf',
			'tpldesinfo'=>'小图标为正方形300x300px。不支持更换颜色风格',
			'attr'=>'bgs thumb focu',
			'sort'=>65,
		),
		array(
			'tpltypeid'=>66,
			'tplview'=>'cate166.png',
			'tpltypename'=>'166_index_6dgbf',
			'tpldesinfo'=>'小图标为正方形300x300px。不支持更换颜色风格',
			'attr'=>'bgs thumb focu',
			'sort'=>66,
		),
		array(
			'tpltypeid'=>67,
			'tplview'=>'cate167.png',
			'tpltypename'=>'167_index_6dgbf',
			'tpldesinfo'=>'小图标为正方形300x300px，图片建议360x200px。不支持更换颜色风格',
			'attr'=>'bgs thumb focu',
			'sort'=>67,
		),
		array(
			'tpltypeid'=>68,
			'tplview'=>'cate168.png',
			'tpltypename'=>'168_index_6dgbf',
			'tpldesinfo'=>'小图标为正方形300x300px，图片建议360x200px。不支持更换颜色风格',
			'attr'=>'bgs thumb focu',
			'sort'=>68,
		),
		array(
			'tpltypeid'=>69,
			'tplview'=>'cate169.png',
			'tpltypename'=>'169_index_6dgbf',
			'tpldesinfo'=>'小图标为正方形300x300px。不支持更换颜色风格',
			'attr'=>'bgs thumb focu',
			'sort'=>69,
		),
		array(
			'tpltypeid'=>70,
			'tplview'=>'cate170.png',
			'tpltypename'=>'170_index_6dgbf',
			'tpldesinfo'=>'小图标为正方形300x300px。不支持更换颜色风格',
			'attr'=>'bgs thumb focu',
			'sort'=>70,
		),
		array(
			'tpltypeid'=>71,
			'tplview'=>'cate171.png',
			'tpltypename'=>'171_index_stbn',
			'tpldesinfo'=>'小图标为正方形300x300px。不支持更换颜色风格',
			'attr'=>'bgs thumb focu',
			'sort'=>71,
		),
		array(
			'tpltypeid'=>72,
			'tplview'=>'cate172.png',
			'tpltypename'=>'172_index_44g3',
			'tpldesinfo'=>'小图标为正方形300x300px。不支持更换颜色风格',
			'attr'=>'bgs thumb focu',
			'sort'=>72,
		),
		array(
			'tpltypeid'=>73,
			'tplview'=>'cate173.png',
			'tpltypename'=>'173_index_6dff',
			'tpldesinfo'=>'小图标为正方形300x300px。不支持更换颜色风格',
			'attr'=>'bgs thumb focu',
			'sort'=>73,
		),
		array(
			'tpltypeid'=>74,
			'tplview'=>'cate174.png',
			'tpltypename'=>'174_index_gh46',
			'tpldesinfo'=>'小图标为正方形300x300px。不支持更换颜色风格',
			'attr'=>'bgs thumb focu',
			'sort'=>74,
		),
		array(
			'tpltypeid'=>75,
			'tplview'=>'cate175.png',
			'tpltypename'=>'175_index_6deh',
			'tpldesinfo'=>'小图标为正方形300x300px。不支持更换颜色风格',
			'attr'=>'bgs thumb focu',
			'sort'=>75,
		),
		array(
			'tpltypeid'=>76,
			'tplview'=>'cate176.png',
			'tpltypename'=>'176_index_sda3',
			'tpldesinfo'=>'小图标为正方形300x300px。不支持更换颜色风格',
			'attr'=>'bgs thumb focu',
			'sort'=>76,
		),
		array(
			'tpltypeid'=>77,
			'tplview'=>'cate177.png',
			'tpltypename'=>'177_index_gh5f',
			'tpldesinfo'=>'小图标为正方形300x300px。不支持更换颜色风格',
			'attr'=>'bgs thumb focu',
			'sort'=>77,
		),
		array(
			'tpltypeid'=>78,
			'tplview'=>'cate178.png',
			'tpltypename'=>'178_index_shfr',
			'tpldesinfo'=>'不支持更换颜色风格',
			'attr'=>'bgs focu lis',
			'sort'=>78,
		),
		array(
			'tpltypeid'=>79,
			'tplview'=>'cate179.png',
			'tpltypename'=>'179_index_4g4f',
			'tpldesinfo'=>'不支持更换颜色风格',
			'attr'=>'bgs focu lis',
			'sort'=>79,
		)
	
	);
	
	
return $tpl;

?>